[package]
name = "w5500-json"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = { version = "0.7.5", default-features = false }

panic-halt = { version = "1.0.0", default-features = false }

embassy-executor = { version = "0.9.1", default-features = false, features = ["arch-cortex-m", "executor-thread"] }
embassy-rp = { version = "0.9.0", default-features = false, features = ["rp2040", "critical-section-impl", "time-driver", "default"] }
embassy-time = { version = "0.5.0", default-features = false }
