[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "link-arg=--nmagic",  # don't use magic page alignment
    "-C", "link-arg=-Tlink.x",  # use a custom linker script
    "-C", "no-vectorize-loops", # disable LLVM loop vectorization
]